# Generated by Django 5.2.3 on 2025-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('onboarding_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chassis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('ownership_id', models.IntegerField(blank=True, null=True)),
                ('provider_id', models.IntegerField(blank=True, null=True)),
                ('oem_id', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('load_capacity', models.IntegerField(blank=True, null=True)),
                ('battery_no', models.CharField(blank=True, max_length=100, null=True)),
                ('charger_no', models.CharField(blank=True, max_length=100, null=True)),
                ('stepney', models.BooleanField(blank=True, null=True)),
                ('toolkits', models.BooleanField(blank=True, null=True)),
                ('iot_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('iot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_copy', models.BooleanField(blank=True, null=True)),
                ('rc_upload', models.FileField(blank=True, null=True, upload_to='rc_uploads/')),
                ('insurance_copy', models.BinaryField(blank=True, null=True)),
                ('insurance_renewal_due', models.DateTimeField(blank=True, null=True)),
                ('lease_per_month', models.FloatField(blank=True, null=True)),
                ('number_plate_photo', models.BinaryField(blank=True, null=True)),
                ('branding_photo_1', models.BinaryField(blank=True, null=True)),
                ('branding_photo_2', models.BinaryField(blank=True, null=True)),
                ('branding_photo_3', models.BinaryField(blank=True, null=True)),
                ('branding_photo_4', models.BinaryField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('hub_address', models.CharField(blank=True, max_length=255, null=True)),
                ('parking_location', models.CharField(blank=True, max_length=255, null=True)),
                ('returning_date', models.DateTimeField(blank=True, null=True)),
                ('returning_reason', models.TextField(blank=True, null=True)),
                ('replacement_vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('rto_compliance', models.BooleanField(blank=True, null=True)),
                ('allowed_kms', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'InventoryManagement',
                'managed': False,
            },
        ),
    ]
